# Generated by Django 2.1.15 on 2020-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('fitnesslvl', models.CharField(max_length=400)),
                ('energylvl', models.CharField(max_length=400)),
                ('recentissue', models.CharField(max_length=400)),
                ('prescription', models.CharField(max_length=400)),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
            ],
        ),
    ]
